=== LenouarMiloud/PracticalWorkMaster_II/TP XML/TP01/exo7/exo7.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT agenda (personne+)> 
<!ELEMENT personne (nom, prenom, prenom2?,adresse,telephone*)> 
<!ATTLIST personne 
                    situation (célibataire|marié|pacsé|concubinage) #REQUIRED                                      
                    id_personne ID #REQUIRED                                      
                    id_connait IDREFS  #IMPLIED
> 
<!ELEMENT nom (#PCDATA)> 
<!ATTLIST nom titre (M|Mlle|Mme) #REQUIRED> 
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT prenom2 (#PCDATA)> 
<!ATTLIST prenom2 prenom3 CDATA #IMPLIED> 
<!ELEMENT adresse  (rue,code_postal,ville)>
<!ELEMENT telephone (#PCDATA)> 
<!ATTLIST telephone Type (perso|bureau|portable) #REQUIRED > 
<!ELEMENT rue (#PCDATA)> 
<!ELEMENT code_postal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>

=== LenouarMiloud/PracticalWorkMaster_II/TP XML/TP01/exo7/exo7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "exo7.dtd">
<agenda>
    <personne situation="cÃ©libataire" id_personne="root">
        <nom titre="M">SANGARE</nom>
        <prenom>Moussa</prenom>
        <prenom2 prenom3="Keita">Pasto</prenom2>
        <adresse>
            <rue>14 rue Ali Maachi</rue>
            <code_postal>14000</code_postal>
            <ville>Tiaret</ville>
        </adresse>
        <telephone Type="bureau">09876654323</telephone>
    </personne>
</agenda>
