=== LenouarMiloud/PracticalWorkMaster_II/TP XML/TP01/exo6/agenda.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT agenda (personne+)>
<!ELEMENT personne (nom,prenom,adresse,tel)>
<!ELEMENT adresse (rue,code_postal,ville)>
<!ELEMENT nom (#PCDATA)> 
<!ELEMENT prenom (#PCDATA)>  
<!ELEMENT tel (#PCDATA)> 
<!ELEMENT rue (#PCDATA)> 
<!ELEMENT code_postal (#PCDATA)> 
<!ELEMENT ville (#PCDATA)>

=== LenouarMiloud/PracticalWorkMaster_II/TP XML/TP01/exo6/tp1_exo6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <personne>
        <nom></nom>
        <prenom></prenom>
        <adresse>
            <rue></rue>
            <code_postal></code_postal>
            <ville></ville>
        </adresse>
        <tel></tel>
    </personne>
</agenda>
