=== LenouarMiloud/PracticalWorkMaster_II/TP XML/TP02/exo3/td_2_exo3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="bibliographie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title"></xs:element>
                <xs:element name="auteur">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id"></xs:element>
                            <xs:element name="nom"></xs:element>
                            <xs:element name="prenom"></xs:element>
                            <xs:element name="gender">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="homme" />
                                        <xs:element name="femme" />
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tome">
                    <xs:simpleType>
                        <xs:restriction base="xs:nonNegativeInteger"></xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="date" type="xs:date"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LenouarMiloud/PracticalWorkMaster_II/TP XML/TP02/exo3/td_2_exo31.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliographie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/TP_Master/TP%20XML/TP02/exo3/td_2_exo3.xsd">
    <title>    </title>
    <auteur>
        <id>     </id>
        <nom>     </nom>
        <prenom>    </prenom>
        <gender>
            <femme>   </femme>
        </gender>
    </auteur>
    <tome>70</tome>
    <date>2016-03-04</date>
</bibliographie>
